name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your preferred branch

jobs:
  deploy:
    runs-on: self-hosted  # This uses the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /path/to/key.pem ubuntu@<EC2-Public-DNS> "
            cd /var/www/html &&
            git pull origin main &&
            sudo systemctl restart apache2
          "
