name: Deploy to Selected Server

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Select the server to deploy to'
        required: true
        default: 'server1'
        type: choice
        options:
          - server1
          - server2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ssh_key
        chmod 600 ssh_key
        if [ "${{ github.event.inputs.server }}" == "server1" ]; then
          scp -o StrictHostKeyChecking=no -i ssh_key -r * ubuntu@ec2-13-60-66-32.eu-north-1.compute.amazonaws.com:/var/www/html/
        elif [ "${{ github.event.inputs.server }}" == "server2" ]; then
          scp -o StrictHostKeyChecking=no -i ssh_key -r * ubuntu@ec2-16-171-165-187.eu-north-1.compute.amazonaws.com:/var/www/html/
        fi
      shell: bash

