name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-60-31-134.eu-north-1.compute.amazonaws.com <<EOF
          sudo rm -rf /var/www/html/*
          sudo git clone https://github.com/your-username/your-repo-name.git /var/www/html/
          sudo systemctl restart apache2
        EOF

